import Head from "next/head";
import { Inter } from "@next/font/google";
import { collectionsApi } from "@/entities/Product";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, isLoading, isError } = collectionsApi.useFetchAllQuery();

  return (
    <>
      <Head>
        <title>Glasses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <pre>{data?.collections}</pre>
      </main>
    </>
  );
}
