import Head from "next/head";
import { Inter } from "@next/font/google";
import { collectionsApi } from "@/entities/Product";
import { setupStore, wrapper } from "@/app/store/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

let store = setupStore();

const Home = () => {
  const { data, isLoading, isError } = collectionsApi.useFetchAllQuery();

  return (
    <>
      <Head>
        <title>Glasses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{JSON.stringify(data && data?.collections)}</div>
      </main>
    </>
  );
};

//

export default Home;
