import Head from "next/head";
import { Inter } from "@next/font/google";
import {
  collectionsSlice,
  fetchCollections,
  fetchGlasses,
  filtersSlice,
} from "@/entities/Product";
import { NextThunkDispatch, setupStore, wrapper } from "@/app/store/store";
import { Provider } from "react-redux";
import { useAppSelector, useAppDispatch } from "@/shared/hooks/redux";
import { useEffect } from "react";
import { GetServerSideProps, NextPageContext } from "next";

const inter = Inter({ subsets: ["latin"] });

let store = setupStore();

const Home = ({ test }) => {
  const data = useAppSelector((state) => state.collectionsState);

  const dispatch = useAppDispatch();

  useEffect(() => {
    // dispatch(fetchCollections());
  }, [dispatch]);
  return (
    <>
      <Head>
        <title>Glasses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        123
        <div>{JSON.stringify(data && data?.collections)}</div>
      </main>
    </>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    await store.dispatch(fetchCollections() as any);
  }
);
export default Home;
